spring:
  application:
    name: chatroom-service
  liquibase:
    change-log: classpath:db/migration/v1/changelog.yaml
  mail:
    host: smtp.gmail.com
    port: 587
    username: emailem@gmail.com
    password: isdjxozvwvcqczfr
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/chatroom}
    username: ${DB_USERNAME:head}
    password: ${DB_PASSWORD:456890}
server:
  http2:
    enabled: true
  port: 8443
  host: localhost
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: springboot
    keyStoreType: PKCS12
    keyAlias: tomcat

logging:
  level:
    org.springframework.security: TRACE

web-client:
  url: ${WC_URL:http://localhost:8080}
jwt:
  cookie-token-key: '{"kty":"oct","k":"956PBFst1FguLr5irJD-aQ"}'
  token-days-to-live: 1
user-account:
  recovery-days: 181


